### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by csokafor** [caabernathy/quizzer#2]
I get the error below when I try to install the android apk of the project.

Execution failed for task ':app:installDebug'.

> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to finalize session : INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES: New package has a different signature: com.quizzer

**Comment by 3barney** [comment]
@csokafor i think you should uninstall the existing apk and perform a re-installation again

**Comment by csokafor** [comment]
Thanks @3barney. I was able to run it on a different device.
